services:
  web_server:
    container_name: web_server
    build: web_server
    ports:
      - "80:80"
    volumes:
      - ../src/public:/srv/www
  php:
    container_name: php
    build: php
    links:
      - redis
      - mysql
    volumes_from:
      - web_server
    environment:
      REDIS_PORT: 6379
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
  mysql:
    container_name: mysql
    build: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./mysql/templates/database.env
  node:
    container_name: node
    build: node
    volumes_from:
      - web_server
